services:

  stp-orchestration-service:
    container_name: bstp-orchestration-decision-service
    image: dev.local/bamoe-demos/bamoe-decision-labs-stp-orchestration-service:1.0.0
    platform: linux/amd64
    ports:
      - 8080:8080
      
  