################################################
# REST Endpoint Tests
################################################

@local.host.url = http://localhost:8081
@remote.host.url = https://quarkus-banking-deposit-service-bamoe-demos.apps-crc.testing
@host={{remote.host.url}}
@contentType = application/json

################################################
# Get IBM BAMOE Version
################################################

GET {{host}}/banking-deposit-service/version HTTP/1.1
content-type: text/plain

{
}

################################################
# Process Deposit
################################################

POST {{host}}/banking-deposit-service/process-deposit HTTP/1.1
content-type: {{contentType}}

{
  "amount": 650,
  "maxAvailabilityAmount": 500,
  "type": "PersonalCheck",
    "customer": {
      "accountNumber": "ABC123",
      "lastName": "White",
      "firstName": "Walter",
      "age": 61
    }
}


################################################
# Process Deposits
################################################

POST {{host}}/banking-deposit-service/process-deposits HTTP/1.1
content-type: {{contentType}}

[
  {
    "amount": 650,
    "maxAvailabilityAmount": 500,
    "type": "PersonalCheck",
     "customer": {
        "accountNumber": "ABC123",
        "lastName": "White",
        "firstName": "Walter",
        "age": 61
     }
  },
  {
    "amount": 1750,
    "maxAvailabilityAmount": 500,
    "type": "PersonalCheck",
     "customer": {
        "accountNumber": "ABC123",
        "lastName": "White",
        "firstName": "Walter",
        "age": 61
     }
  },
  {
    "amount": 1750,
    "maxAvailabilityAmount": 500,
    "type": "PayrollCheck",
     "customer": {
        "accountNumber": "ABC123",
        "lastName": "White",
        "firstName": "Walter",
        "age": 61
     }
  }]