services:

  classic-decision-service:
    container_name: classic-decision-service
    image: dev.local/bamoe-demos/classic-decision-service:1.0.0
    platform: linux/amd64
    ports:
      - 8081:8080
      
  