################################################
# REST Endpoint Tests
################################################

@local.host.url = http://localhost:8082
@remote.host.url = https://sb-traffic-violation-service-bamoe-v931-demos.apps-crc.testing
@host={{remote.host.url}}
@contentType = application/json

################################################
# Version
################################################

GET {{host}}/traffic-violation-service/version HTTP/1.1
content-type: text/plain

{
}

################################################
# Process Traffic Violation
################################################

POST {{host}}/traffic-violation-service/process-traffic-violation HTTP/1.1
content-type: {{contentType}}

{
  "violation": {
    "date": "2022-03-10",
    "type": "speed",
    "speedLimit": 100,
    "actualSpeed": 120
  },
  "driver": {
    "name": "Walter White",
    "age": 55,
    "state": "Albuquerque",
    "city": "New Mexico"
  }
}