################################################
# REST Endpoint Tests
################################################

@local.host.url = http://localhost:8082
@remote.host.url = https://quarkus-traffic-violation-service-bamoe-demos.apps-crc.testing
@host={{local.host.url}}
@contentType = application/json

GET {{host}}/traffic-violation-service/version HTTP/1.1
content-type: text/plain

{
}

POST {{host}}//traffic-violation-service/process-traffic-violation HTTP/1.1
content-type: {{contentType}}

{
  "violation": {
    "date": "2022-03-10",
    "type": "speed",
    "speedLimit": 100,
    "actualSpeed": 120
  },
  "driver": {
    "name": "Walter White",
    "age": 55,
    "state": "Albuquerque",
    "city": "New Mexico",
    "points": 2
  }
}